const a = [
  "5-HTP", "5-hydroxytryptophan", "Griffonia",
  "Griffonia simplicifolia seed extract",
  "Acetyl-L-carnitine", "N-Acetyl-L-Carnitine",
  "Agmatine Sulfate", "Agmapure",
  "Alpha-Lipoic Acid", "ALA", "리포산", "α-Lipoic acid",
  "R-Lipoic acid", "Lipoic acid", "ALA",
  "Aphanizomenon flos-aquae", "AFA",
  "Microcystin", "마이크로시스틴", "미소시스틴",
  "Arachidonic acid",
  "Bacopa", "Brahmi",
  "Berberine", "베르베린",
  "Black Cohosh", "블랙 코호시", "black snake root", "Actaea racemosa", "승마", "Cimicifuga recomosa",
  "Buckthorn", "Rhamnus frangula", "벅턴",
  "Butea superba", "Creeping butea", "Butea gum tree", "Redkwaokrua",
  "Butterfly Pea",
  "Cat's Claw", "Uncaria Tomentosa",
  "Catuaba",
  "Charcoal", "차콜", "숯", "Activated charcoal",
  "Chromium Picolinate", "피콜린산 크롬",
  "Citicoline", "cognizen",
  "Clubmoss Extract", "석송", "石松", "Clubmoss", "ChineseClubmoss",
  "Colt's foot", "Coltsfoot", "Farfarae flos", "Ass's foot", "Bull's foot", "Coughwort", "Farfara", "Foal's wort", "Fieldhove", "Horse hoof", "Horse-foot", "Horse-shoe", "Horsehoof", "Tussilago farfara Linné", "관동", "款冬",
  "Devil's Claw Root", "Harpagophytum procumbens",
  "DHEA", "Dehydroepiandrosterone",
  "Diindolylmethane", "DIM",
  "Diosmin",
  "Echinacea spp", "에키네시아 속",
  "Epimedium sagittatum", "Epimedium Grandiflorum", "Horny goat weed", "이카린",
  "Forsythia suspensa extract", "연교",
  "Fur Seal", "물개", "オットセイエキス",
  "Gamma-aminobutyric acid", "GABA",
  "Garcinia Quaesita",
  "Germanium", "게르마늄",
  "Goldenseal Root", "OX-EYE DAISY", "골든씰 뿌리",
  "Guggul Extract", "resin", "guggulsterones", "몰약",
  "Gymnema Sylvestre", "당살초",
  "Hemp", "Cannabis sativa L",
  "Histamine", "Histamine Hydrochloride", "Histamine HCl",
  "Horse Chestnut", "서양칠엽수", "홀스캐슈너츠",
  "Icariin", "이카린",
  "Indian Snake Root", "Rauwolfia serpentina", "인도사목",
  "kaempferia parviflora", "흑생강",
  "Kava kava", "kawa kawa", "Kavain",
  "L-citrulline", "Citrulline Malate",
  "Lobelia", "Rhodea japonica Roth", "만년청", "萬年靑",
  "Longjack", "Eurycoma Longifolia", "Tongkat Ali",
  "L-ornithine", "L-오르니틴",
  "L-Selenomethionine",
  "Magnesium citrate",
  "Magnolia", "magnolia officinalis", "후박",
  "Mamushi", "살모사", "まむし",
  "Melatonin", "멜라토닌",
  "Methylcobalamin", "Methyl-B12", "메틸코발아민", "Active-B12",
  "L-dopa", "Montanoa", "Montanoa Tomentosa",
  "Muira Puama", "Ptychopetalum olacoides",
  "N-acetyl-cysteine", "NAC", "N-acetyl-L-cysteine", "NAC",
  "Orlistat", "오르리스타트",
  "Para-aminobenzoic acid", "PABA", "파바",
  "Phellodendri Cortex", "Phellodendron", "Phellodendron bark", "Phellodendron amurense Ruprecht", "Phellodendron chinense Schneider",
  "Phenylethylamine", "PEA", "β-Phenylethylamine", "β-PEA", "2-Phenethylamine", "β-phenethylamine·Hydrochloride", "β-PEA·HCl",
  "Pinellia Tuber", "Pinellia ternata Breitenbach", "반하", "半夏",
  "Pomegranate Seed", "석류씨", "Pomegranate bark",
  "Poppy", "Papaver somniferum",
  "Pueraria mirifica",
  "Pygeum Africanum", "bark",
  "Raspberry Ketone", "라즈베리케톤",
  "Rhubarb", "Rheum palmatum", "Rheum tanguticum",
  "Rheum officinale Bailon", "대황",
  "Salacia", "사라시아",
  "Scorpion", "scorpio", "Buthus martensii Karsch", "전갈", "全蝎",
  "Senna", "센나",
  "Silver",
  "Slippery Elm", "느릅나무", "유근피", "Ulmus rubra",
  "Synephrine",
  "Vervain", "Verbena", "Verbanalin", "버바인", "마편초", "지상부",
  "Vinpocetine", "빈포세틴", "Vinca minor", "lesser periwinkle",
  "Vitamin K2", "Menaquinone", "MK-4", "MK-7",
  "White willow", "Salix Alba", "흰버드나무",
  "Wild Yam",
  "Yohimbe", "요힘베",
  "Yohimbin", "요힘빈",
  "Zinc citrate",
  "곤약/글루코만난 겔화제",
  "허용되지 않은 타르색소", "E131 Patent blue V",
  "Mucuna Pruriens seed",
  "Magnesium glycinate", "Magnesium diglycinate", "Magnesium bisglycinate",
  "Cassia occidentalis",
  "Terminalia arjuna",
  "Andrographis",
  "Phyllanthus amarus",
  "Shilajit",
  "Buchu leaf", "Agathosma betulina", "Agathosma creunlata",
  "Tejocote root", "Crataegus mexicana",
  "Lithium",
  "1,3-dimethylamylamine", "DMAA", "1,3-dimethylbutylamine", "DMBA", "1,3-디메틸부틸아민",
  "Acetaminotadalafil", "아세트아미노타다라필",
  "Acetyl acid", "아세틸산",
  "Acetylvardenafil", "아세틸바데나필",
  "Adrenaline", "Epinephrine",
  "Ajuga Decumbens", "조개나물", "백하초", "근골초",
  "Aminotadalafil", "아미노타다라필",
  "Anemarrhennae asphodelides", "지모",
  "Avanafil", "아바나필",
  "Belladonna", "벨라돈나", "Atropa belladonna",
  "Benzylsildenafil", "벤질실데나필",
  "Bergenin",
  "Caesalpinia Benthamiana",
  "Carbodenafil", "카보데나필",
  "Cascara sagrada", "카스카라사그라다",
  "Cascaroside", "카스카로사이드",
  "Cha De bugre", "herb powder",
  "Chlorodenafil", "클로로데나필",
  "Chloropretadalafil", "클로로프레타다라필",
  "Chlorosibutramine", "클로로시부트라민",
  "Chlorosipentramine", "클로로시펜트라민",
  "Chromium Argninate",
  "Cinnamyldenafil", "신나밀데나필",
  "Cis-cyclopentyltadalafil", "cis-사이클로펜틸타다라필",
  "Cordia Salicifolia",
  "Couch Grass", "Agropyron repens", "Elymus repens", "개밀",
  "Cyanotis Vaga",
  "Cyclopentynafil", "싸이클로펜티나필",
  "D-chlorpheniramine", "클로로페니라민",
  "Demethylhongdenafil", "데메틸홍데나필",
  "Demethyltadalafil", "데메칠타다라필",
  "Descarbonsildenafil", "데스카본실데나필",
  "desmethylcarbodenafil", "데스메틸카보데나필",
  "Desmethylsibutramine", "데스메틸시부트라민",
  "Desulfovardenafil", "데설포바데나필",
  "Dexamethasone", "덱사메타손",
  "Dichlorodenafil", "디클로로데나필",
  "Didesmethylsibutramine", "디데스메틸시부트라민",
  "Dimethylsildenafil", "디메칠실데나필",
  "Dimethylthiosildenafil", "디메틸치오실데나필",
  "Dithiopropylcarbodenafil", "디치오프로필카보데나필",
  "Dolmite", "돌로마이트", "백운석",
  "DNP", "dinitrophenyl", "Dinitrophenol", "디니트로페놀", "2,4-Dinitrophenol", "2,4-DNP",
  "Ebony", "흑단", "검은나무",
  "Ephedrine", "에페드린",
  "Fenfluramine", "펜플루라민",
  "Fluoxetine", "플루옥세틴",
  "Fucoxanthin",
  "Furosemide", "푸로세미드",
  "Gelsemium Sempervirens", "겔세민", "캐롤라이나 쟈스민",
  "Gendenafil", "겐데나필",
  "Glibenclamide", "글리벤클라미드",
  "Gliclazide", "글리클라짓",
  "Glimepiride", "글리메피리드",
  "Glipizide", "글리피짓",
  "Gravel Root",
  "Homosildenafil", "호모실데나필",
  "homotadalafil", "호모타다라필",
  "Hongdenafil", "홍데나필",
  "Hoodia Cactus powder",
  "Hoodia Gordonii",
  "Hydroxychlorodenafil", "하이드록시클로로데나필",
  "Hydroxyhomosildenafil", "하이드록시호모실데나필",
  "Hydroxyhongdenafil", "하이드록시홍데나필",
  "Hydroxythiohomosildenafil", "하이드록시치오호모실데나필",
  "Hydroxyvardenafil", "하이드록시바데나필",
  "Imidazosagtriazinone", "이미다조사가트리아지논",
  "Isopropylnortadalafil", "이소프로필노르타다라필",
  "Levothyroxine", "레보치록신",
  "Ligustrum Berry",
  "Liothyronine", "리오치로닌",
  "Lumbrokinase", "룸브로키나제", "지렁이",
  "Methylhydroxyhomosildenafil", "메틸하이드록시호모실데나필",
  "Mirodenafil", "미로데나필",
  "Nitrodenafil", "니트로데나필",
  "N-nitrosofenfluramine", "N-니트로소펜플루라민",
  "N-octylnortadalafil", "옥틸노르타다라필",
  "Norneosildenafil", "노르네오실데나필",
  "Norneovardenafil", "노르네오바데나필",
  "Oxilofrine",
  "Oxohongdenafil", "옥소홍데나필",
  "Phenolphthalein", "페놀프탈레인",
  "Piperidinohongdenafil", "피페리디노홍데나필",
  "Prickly Chaff", "Achyranthes aspera",
  "Propoxyphenyl-thioaildenafil", "프로폭시페닐치오아일데나필",
  "Propoxyphenylthiohomosildenafil", "프로폭시페닐치오호모실데나필",
  "Propoxyphenylthiohydroxyhomosildenafil", "프로폭시페닐치오하이드록시호모실데나필",
  "Propoxyphenylthiosildenafil", "프로폭시페닐치오실데나필",
  "Pseudovardenafil", "슈도바데나필",
  "Radix morindae officinalis", "꼭두서니과",
  "Red root bark", "quinna tree bark", "cichona bark", "PavonetKlotzsch", "키나나무",
  "Rhaponticum Carthamoides",
  "Seman Pruni", "도인", "桃仁",
  "Sennoside", "센노사이드",
  "Sibutramine", "시부트라민",
  "Sildenafil", "실데나필",
  "Tadalafil", "타다라필",
  "Thiohomosildenafil", "치오호모실데나필",
  "Thioquinapiperifil", "치오퀴나피페리필",
  "Thiosildenafil", "치오실데나필",
  "Trans-cyclopentyltadalafil", "trans-사이클로펜틸타다라필",
  "Trichopus Zeylanicus",
  "Udenafil", "유데나필",
  "Vardenafil", "바데나필",
  "Veratrum", "White Hellebore", "Veratri Rhizoma et Radix",
  "Xanthoanthrafil", "잔소안트라필",
  "β-methylphenethylamine·Hydrochloride", "β-MPEA·HCl", "β-methylphenethylamine", "β-MPEA",
  "Orthosiphon stamineus",
]

module.exports = a