const a = [
  "5-HTP",
"5-hydroxytryptophan",
"Griffonia",
"Griffonia simplicifolia seed extract",
"Acetyl-L-carnitine",
"N-Acetyl-L-Carnitine",
"Agmatine Sulfate",
"Agmapure",
"Alpha-Lipoic Acid",
"α-Lipoic acid",
"R-Lipoic acid",
"Lipoic acid",
"ALA",
"Aphanizomenon flos-aquae",
"AFA",
"Microcystin",
"Arachidonic acid",
"Bacopa",
"Brahmi",
"Berberine",
"Black Cohosh",
"black snake root",
"Actaearacemosa",
"Cimicifuga recomosa",
"Buckthorn",
"Rhamnus frangula",
"Butea superba",
"Creeping butea",
"Butea gum tree",
"Redkwaokrua",
"Butterfly Pea",
"Cat's Claw",
"Uncaria Tomentosa",
"Catuaba",
"Charcoal",
"Activated charcoal",
"Chromium Picolinate",
"Citicoline",
"cognizen",
"Clubmoss Extract(Clubmoss",
"ChineseClubmoss)",
"Colt's foot",
"Coltsfoot",
"Farfarae flos",
"Ass's foot",
"Bull's foot",
"Coughwort",
"Farfara",
"Foal's wort",
"Fieldhove",
"Horse hoof",
"Horse-foot",
"Horse-shoe",
"Horsehoof",
"Tussilago farfara Linné",
"Devil's Claw Root",
"Harpagophytum procumbens",
"DHEA(Dehydroepiandrosterone)",
"Diindolylmethane(DIM)",
"Diosmin",
"Echinacea spp",
"Epimedium sagittatum",
"Epimedium Grandiflorum",
"Forsythia suspensa extract(Fruit)",
"Fur Seal",
"Gamma-aminobutyric acid",
"Garcinia Quaesita",
"Germanium",
"Goldenseal Root(OX-EYE DAISY)",
"Guggul Extract(resin)",
"guggulsterones",
"Gymnema Sylvestre",
"Hemp(Cannabis sativa L.)",
"Histamine",
"Histamine Hydrochloride",
"Histamine HCl",
"Horse Chestnut",
"Indian Snake Root",
"Rauwolfia serpentina",
"kaempferia parviflora",
"Kava kava",
"kawa kawa",
"KavainL-citrulline(Citrulline Malate)",
"Lobelia",
"Rhodea japonica Roth",
"Longjack",
"Eurycoma Longifolia",
"L-ornithine",
"Magnesium citrate",
"Magnolia(magnolia officinalis)",
"Extract",
"Mamushi",
"Melatonin",
"Methylcobalamin",
"Methyl-B12",
"Active-B12",
"L-dopa",
"Montanoa",
"Montanoa Tomentosa",
"Muira Puama(Ptychopetalum olacoides)",
"N-acetyl-cysteine(NAC)",
"N-acetyl-L-cysteine(NAC)",
"Orlistat",
"Para-aminobenzoic acid(PABA)",
"Phellodendri Cortex",
"Phellodendron",
"Phellodendron bark",
"Phellodendron amurense Ruprecht",
"Phellodendron chinense",
"Schneider",
"Phenylethylamine(PEA)",
"β-Phenylethylamine(β-PEA)",
"2-Phenethylamine",
"β-phenethylamine·Hydrochloride(β-PEA·HCl)",
"Pinellia Tuber",
"Pinellia ternata Breitenbach",
"Pomegranate Seed",
"Pomegranate bark",
"Poppy(Papaver somniferum)",
"Pueraria mirifica",
"Pygeum Africanum (bark)",
"Raspberry Ketone",
"Rhubarb",
"Rheum palmatum",
"Rheum tanguticum",
"Rheum officinale Bailon",
"Salacia",
"Scorpion",
"scorpio",
"Buthus martensii",
"3-dimethylamylamine",
"Karsch",
"Senna",
"Silver",
"69 Slippery Elm",
"Ulmus rubra",
"Synephrine",
"Vervain",
"Verbena",
"Verbanalin",
"Vinpocetine",
"Vinca minor",
"lesser periwinkle",
"Vitamin K2",
"Menaquinone",
"MK-4",
"MK-7",
"White willow",
"Salix Alba",
"Wild YamYohimbe",
"Yohimbin",
"Zinc citrate",
"E131 Patent blue V",
"Mucuna Pruriens seed",
"Magnesium glycinate",
"Magnesium diglycinate",
"Magnesium",
"bisglycinate",
"Cassia occidentalis",
"Terminalia arjuna",
"Andrographis",
"Phyllanthus amarus",
"Shilajit",
"Buchu leaf",
"Agathosma betulina",
"Agathosma creunlata",
"Tejocote root(Crataegus mexicana)",
"Lithium",
"3-dimethylamylamine(DMAA)",
"dimethylbutylamine(DMBA)",
"Acetaminotadalafil",
"Acetyl acid",
"Acetylvardenafil",
"Adrenaline",
"Epinephrine",
"Ajuga Decumbens",
"Aminotadalafil",
"Anemarrhennae asphodelides",
"Avanafil",
"Belladonna",
"Atropa belladonna",
"Benzylsildenafil",
"Bergenin",
"Caesalpinia Benthamiana",
"Carbodenafil",
"Cascara sagrada",
"Cha De bugre(herb powder)",
"Chlorodenafil",
"Chloropretadalafil",
"Chlorosibutramine",
"Chlorosipentramine",
"Chromium Argninate",
"Cinnamyldenafil",
"Cis-cyclopentyltadalafil",
"Cordia Salicifolia",
"Couch Grass",
"Agropyron repens",
"Elymus repens",
"Cyanotis Vaga",
"Cyclopentynafil",
"D-chlorpheniramine",
"Demethylhongdenafil",
"Demethyltadalafil",
"Descarbonsildenafil",
"Desmethylsibutramine",
"Desulfovardenafil",
"Dexamethasone",
"Dichlorodenafil",
"Didesmethylsibutramine",
"Dimethylsildenafil",
"Dimethylthiosildenafil",
"Dithiopropylcarbodenafil",
"Dolmite",
"DNP(dinitrophenyl, Dinitrophenol)",
"2,4-Dinitrophenol",
"2,4-DNP)",
"Ebony",
"Ephedrine",
"Fenfluramine",
"Fluoxetine",
"Fucoxanthin",
"Furosemide",
"Gelsemium Sempervirens",
"Gendenafil",
"Glibenclamide",
"Gliclazide",
"Glimepiride",
"Glipizide",
"Gravel Root",
"Homosildenafil",
"homotadalafil",
"Hongdenafil",
"Hoodia Cactus powder",
"Hoodia Gordonii",
"Hydroxychlorodenafil",
"Hydroxyhomosildenafil",
"Hydroxyhongdenafil",
"Hydroxythiohomosildenafil",
"Hydroxyvardenafil",
"Imidazosagtriazinone",
"Isopropylnortadalafil",
"Levothyroxine",
"Ligustrum Berry",
"Liothyronine",
"Lumbrokinase",
"Methylhydroxyhomosildenafil",
"Mirodenafil",
"Nitrodenafil",
"N-nitrosofenfluramine",
"N-octylnortadalafil",
"Norneosildenafil",
"Norneovardenafil",
"Oxilofrine",
"Oxohongdenafil",
"Phenolphthalein",
"Piperidinohongdenafil",
"Prickly Chaff(Achyranthes aspera)",
"Propoxyphenyl-thioaildenafil",
"Propoxyphenylthiohomosildenafil",
"Propoxyphenylthiohydroxyhomosildenafil",
"Propoxyphenylthiosildenafil",
"Pseudovardenafil",
"Radix morindae officinalis",
"Red root bark",
"quinna tree bark",
"cichona bark",
"PavonetKlotzsch",
"Rhaponticum Carthamoides",
"Seman Pruni",
"Sennoside",
"Sibutramine",
"Sildenafil",
"Tadalafil",
"Thiohomosildenafil",
"Thioquinapiperifil",
"Thiosildenafil",
"Trans-cyclopentyltadalafil",
"Trichopus Zeylanicus",
"Udenafil",
"Vardenafil",
"Veratrum",
"White Hellebore",
"Veratri Rhizoma et Radix",
"Xanthoanthrafil",
"β-methylphenethylamine·Hydrochloride(β-MPEA·HCl)",
"β-methylphenethylamine (β-MPEA)",
"Orthosiphon stamineus",
"L-CITRULLINE",
"RASPBERRY KETONES",
"5-HTP",
"5HTP",
"CBD",
"PABA",
"NAC",
"HORNY GOAT WEED",
"YOHIMBINE",
"RASPBERRY KETON",
"YOHIMBE",
"Forsythia suspensa",
"Echinacea purpurea",
"BSE",
"DHEA",
"Viagra",
"AGMATINE SULFATE",
"Diindolylemothune",
"DIM",
"BINPOCETINE",
"CLUBMOSS",
"Diindolylmethane",
"muira-puama",
"SLIPPELY ELM",
"EPIMEDIUM",
"CASCARA",
"MUCUNA",
"MAGNOPA",
"bacopa",
"DEXTROMETHORPHAN HBR",
"Ginkgo biloba Leaf",
"X-TEND",
"MUIRA PUAMA",
"HORNEY GOAT WEED",
"GINKGO BILOBA",
"PYGEUM",
"SLIPPERY ELM",
"BETA beta phenethylamine",
"L-citulline",
"finpecia",
"Senna lwaf",
"leaves",
"ECHINACEA",
"Beta-methylphenethylamine·Hydrochloride(β-MPEA·HCl)",
"Beta-methylphenethylamine (β-MPEA)",
"Caffeine",
"Poppy",
"Hemp",
"L-citrullin",
"Citrulline Malate",
"Beta-phenethylamine·Hydrochloride",
"β-MPEA",
"β-MPEA·HCl",
"desmethylcarbodenafil",
"Icarin",
"IcarIin",
"N-acetyl-cysteine",
"Para-aminobenzoic acid",
"β-Phenylethylamine",
"BPEA",
"Phenylethylamine",
"PEA",
"Povidone",
"iodine",
"Propoxyphenyl-Thiosildenafil",
"Propoxyphenylthioaildenafil",
"Isoproylnortadalafil",
"SemanPruni",
"Forsythiasuspensaextract",
"Fruit",
"Magnolia",
"magnoliaofficinalis",
"CouchGrass",
"1-dimethylbutylamine",
"3-dimethylbutylamine",
"DMBA",
"Kavain",
"Dolomite",
"Gelsemine Sempervirens",
"L-Selenomethionine",
"L-Selenomethionine",
"DNP",
"dinitrophenyl",
"Dinitrophenol",
"Agmapure",
"Aphanizomenon flos-aquae",
"ALA",
"Brahmi",
"KavainL-citrulline",
"Goldenseal Root",
"AFA",
"OX-EYE DAISY",
"Tussilago farfara Linné",
"Buckthorn",
"Rhamnus frangula",
"α-Lipoic acid",
"ChineseClubmoss",
"Dehydroepiandrosterone",
"magnolia officinalis",
"E131",
"Lipoic acid",
"N-acetyl-L-cysteine",
"citrate",
"B06XG11TQ4",
"bovine",
"cow",
"beef",
"YOHIMBEE"
]

module.exports = a